# Site settings
title: Hackathon for Humanity
email: h4h@mst.edu
permalink: pretty

description: >
  Hackathon for Humanity is part of Missouri S&T's Golden Jubilee
  Celebration, honoring the department's 50th anniversary.

baseurl: ""

url: "http://h4h@mst.edu" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
