# Site settings
title: Hackathon for Humanity
# email: your-email@domain.com
permalink: pretty

description: >
  Hackathon for Humanity is part of Missouri S&T's Golden Jubilee
  Celebration, honoring the department's 50th anniversary.

baseurl: ""

url: "http://compsci-hfh.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
